import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Jua } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
const jua = Jua({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-jua',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={`${jua.className}`}>
      <body>{children}</body>
    </html>
  );
}
